### ISSUE TITLE
Use `StoreContext` exported by RoactRodux

### ISSUE THREAD

**Issue by qromp** [SolarHorizon/rodux-hooks#4]
Currently, in order to use the Rodux hooks in child components, we need to pass the context exported by Rodux Hooks next to `RoactRodux.StoreProvider` at top level of the tree.
By using the `StoreContext` exported by RoactRodux, the above step is no longer necessary.

See: https://github.com/Roblox/roact-rodux/blob/master/src/StoreContext.lua

**Comment by SolarHorizon** [comment]
Hi, nice suggestion!

While this definitely makes it easier for people who are using roact-rodux to manage any class components in their projects, I feel like that probably does not apply to the majority of people using this library. Rodux-hooks uses its own context internally to handle this without an extra dependency which I think is fine. People using roact-rodux can pass its context to `useCustomDispatch` and `useCustomSelector` to avoid using two providers.

**Comment by qromp** [comment]
Now that makes sense why it uses the custom context internally. (I've wondered why)

As I described above, this simple solution would save the time to wrap a Roact tree with the store provider every time, but as you said, this solution does not apply to everyone using this library.

I guess I'll make a fork of `rodux-hooks` that is aimed specifically only for use with RoactRodux.

Thank you for the clarification!  😄
